window.ToyShopData = {
  categories: [
    { title: "Action Toys", icon: "fa-mask", gradient: "cat-pink" },
    { title: "Dolls & Barbie", icon: "fa-crown", gradient: "cat-lavender" },
    { title: "Remote Cars", icon: "fa-car-side", gradient: "cat-blue" },
    { title: "Educational Toys", icon: "fa-brain", gradient: "cat-yellow" },
    { title: "LEGO & Blocks", icon: "fa-cubes", gradient: "cat-cream" },
    { title: "Plush Toys", icon: "fa-heart", gradient: "cat-pink" },
    { title: "Video Games", icon: "fa-gamepad", gradient: "cat-lavender" },
    { title: "Baby Toys", icon: "fa-baby", gradient: "cat-blue" },
  ],
  products: [
    {
      id: "teddy-xl",
      title: "Teddy Bear XL",
      image: "images/teddy.svg",
      price: 38,
      oldPrice: 59,
      rating: 5,
      badge: "Soft Pick",
    },
    {
      id: "rocket-kit",
      title: "Space Rocket Kit",
      image: "images/rocket.svg",
      price: 45,
      oldPrice: 69,
      rating: 5,
      badge: "STEM",
    },
    {
      id: "dream-house",
      title: "Barbie Dream House",
      image: "images/dollhouse.svg",
      price: 74,
      oldPrice: 119,
      rating: 5,
      badge: "Popular",
    },
    {
      id: "rc-racing-car",
      title: "RC Racing Car",
      image: "images/car.svg",
      price: 52,
      oldPrice: 78,
      rating: 4,
      badge: "New",
    },
    {
      id: "dino-robot",
      title: "Dino Robot",
      image: "images/dino-robot.svg",
      price: 62,
      oldPrice: 92,
      rating: 4,
      badge: "Smart",
    },
    {
      id: "learning-puzzle",
      title: "Learning Puzzle Set",
      image: "images/blocks.svg",
      price: 31,
      oldPrice: 48,
      rating: 5,
      badge: "Creative",
    },
  ],
  testimonials: [
    {
      name: "Maya R.",
      role: "Mom of two",
      avatar: "MR",
      quote: "The site feels calm and premium, and the learning toys were easy to compare.",
    },
    {
      name: "Daniel P.",
      role: "Birthday planner dad",
      avatar: "DP",
      quote: "My son picked the racing car in seconds. The cart and mobile menu are very smooth.",
    },
    {
      name: "Ari S.",
      role: "New parent",
      avatar: "AS",
      quote: "Cute without feeling busy. The categories helped us find baby toys quickly.",
    },
    {
      name: "Lina K.",
      role: "Aunt and gift expert",
      avatar: "LK",
      quote: "The weekend sale and soft visuals made gift shopping feel effortless.",
    },
  ],
};
